github: PriyabrataMo
open_collective: Quotica
ko_fi: shvmmshra
buy_me_a_coffee: shvmmshra
custom:
  [
    'https://checkout.dodopayments.com/buy/pdt_CZmJxGkeWtrmRFO0hznJy?quantity=1&redirect_url=https://quotica.fun',
  ]
